# Profil
app.profile.name=dev

# Konfiguracja bazy (na razie taka sama jak prod)
baza.sterownik=org.postgresql.Driver
baza.ip=localhost
baza.port=5432
baza.nazwa=baza_serwisu
baza.protokol=jdbc:postgresql:
baza.uzytkownik=admin
baza.haslo=haslo

spring.jpa.show-sql=true

# DEV – pozwala automatycznie aktualizować schemat
spring.jpa.hibernate.ddl-auto=update

# Usługa zewnętrzna
_service.name=vpic.nhtsa.dot.gov
_service.port=443
_service.api_path=/api/vehicles/decodevinvalues/%s?format=json
